sources:
  greenhouse:
    enabled: true
    boards:
    - found
    - omadahealth
    - smartsheet
    - gomotive
    - canonical
    - gleanwork
    - dv01
    - climateai
    - grafanalabs
    - correlationone
    - truebill
    - nansen
    - gofundme
    - inthepocket
    - levio
    - webflow
    - celonis
    - thumbtack
    - appier
    - aurosglobal
    - datacamp
    - kalepa
    - capco
    - mavensecuritiesholdingltd
    - cbeyondata
    - via
    - harrys
    - startcampus
    - samsara
    - hightouch
    - omguk
    - airbnb
    - asana
    - customerio
    - 6sense
    - braze
    - moloco
    - sproutsocial
    - taskrabbit
    - remotecom
    - trace3
    - ezcaterinc
    - consensys
    - xapo61
    - perfectserve
    - gitlab
    - knowbe4
    - dbtlabsinc
    - idme
    - 2k
    - deepintent
    - axios
    - alpaca
    - similarweb
    - cloudflare
    - udacity
    - strivehealth
    - eyeo
    - soundcloud71
    - berlinbrands
    - flywheeldigital
    - techstars57
    - doctolib
    - zenjob
    - urbansportsclub
    - yext
    - wheely
    - tripadvisor
    - xai
    - deepmind
    - digitalextremes
    - flagstone
    - drweng
    - wayve
    - reddit
    - travix
    - adyen
    - butternutbox
    - modulrfinance
    - twosixtechnologies
    - figma
    - pomelocare
    - appliedintuition
    - applovin
    - anthropic
    - distantjob
    - shopmonkey
    - stripe
    - roblox
    - square
    - snapchat
    - pinterest
    - lyft
    - dropbox
    - discord
    - okta
    - openai
    - mistralai
    - perplexity
    - midjourney
    - scaleai
    - togetherai
    - databricks
    - huggingface
    - hashicorp
    - confluent
    - postman
    - notion
    - loom
    - zapier
    - canva
    - snyk
    - plaid
    - coinbase
    - moonpay
    - ripple
    - chainlink
    - ramp
    - brex
    - chime
    - nerdwallet
    - monzo
    - revolut
    - datadog
    - elastic
    - mongodb
    - fastly
    - starlingbank
    - checkout
    - deliveryhero
    - hellofresh
    - personio
    - getyourguide
    - bolt
    - klarna
    - spotify
    - mollie
    - backmarket
    - mirakl
    - hubspot
    - duolingo
    - snowflake
    - riotgames
    - zyngacareers
    - pokemoncareers
    - unity
    - bungie
    - thatgamecompany
    - scopely
    - pubgemea
    - seconddinner
    - evoplaygames
    content: true
